project:
  type: website
  output-dir: docs

website:
  title: "Agentes Químicos e Biológicos - Novos Saberes e Olhares"
  description: "Novos saberes e olhares"
  navbar:
    left:
      - href: index.qmd
        text: Início
      - href: welcome.qmd
        text: Boas vindas
    background: light
    logo: /imagens/logo_ufg_vert.png
    logo-alt: "Logo UFG"
    title: false
    collapse-below: lg
      
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



