project:
  type: website
  output-dir: docs

website:
  title: "Gestão de Riscos Químicos em Laboratórios Acadêmicos"
  # description: ""
  navbar:
    left:
      - href: index.qmd
        text: Início
      - href: welcome.qmd
        text: Boas vindas
    background: light
    logo: /imagens/logo_ufg_vert.png
    logo-alt: "Logo UFG"
    title: false
    collapse-below: lg
      
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



