project:
  type: website
  output-dir: site

website:
  title: "Agentes Químicos e Biológicos - Novos Saberes e Olhares"
  description: "Novos saberes e olhares"
  navbar:
    right:
      - href: index.qmd
        text: Início
      - href: welcome.qmd
        text: Boas vindas
      
format:
  html:
    theme: cosmo
    css: custom.scss
    toc: true



