---
title: "Agentes Químicos e Biológicos - Novos Saberes e Olhares"
author: "Tiago Dias"
lang: pt-BR
format: 
    revealjs:
        #logo: "imagens/logo_ufg.png"
        width: 1600
        height: 900
        self-contained: false
        incremental: false
        footer: DAD/PROPESSOAS/UFG - Set/2023
        theme: ["custom.scss"]
        slide-number: c/t
        show-slide-number: all
        hash-type: number
        preview-links: false
---

# Bem vindos(as)!

## Tiago Dias {.center .aboutmeslide}

- Sobre mim

    - _Químico_

    - Laboratório de Nutrição e Análise de Alimentos - FANUT/UFG

- Contato

    - Fone: (62)3209-6270 Ramal 217

    - e-mail: _tiagodias@ufg.br_

# Agentes químicos: toxicologia e segurança

## Objetivo geral

Apresentar aos servidores novos saberes e olhares em relação aos agentes químicos presentes em seus ambientes de trabalho.

## Conteúdo programático

- ***27/Set e 29/Set:*** Contextualização sobre as **propriedades químicas** e sua relação com a **toxicologia** e **segurança** laboratorial

    - Introduzir conceitos de segurança química e toxicologia

    - Conhecer os diferentes agentes químicos, formas de contaminação, ação no organismo e meios de prevenção e controle.

    - Relacionar as normas técnicas da ABNT aos conhecimentos sobre as propriedades dos agentes químicos e seus perigos.

- ***11/Out:*** Produtos Químicos - do recebimento no laboratório ao descarte.

    - Demonstrar procedimentos de segurança no fluxo dos produtos em laboratórios, desde o recebimento até o descarte para coleta;

## 

